### ISSUE TITLE
Deprecate  in favor of - ipfs-message-port-* 

### ISSUE THREAD

**Issue by lidel** [ipfs-inactive/ipfs-postmsg-proxy#37]
@Gozala created universal libraries for sharing API instance across message port:

- https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs-message-port-server
- https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs-message-port-client
- https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs-message-port-protocol

I believe we should:
1. Deprecate this on NPM with message suggesting use of upstream `ipfs-message-port-server` and `ipfs-message-port-client` 
2. Archive this repo and move it to https://github.com/ipfs-inactive/

@alanshaw thoughts?

**Comment by alanshaw** [comment]
SGTM it's very out of date at this point anyway.

**Comment by lidel** [comment]
@alanshaw this slipped through my notifications – mind making me collaborator on NPM?

I've updated README and would like to make a path release to trigger docs update and then deprecate this on NPM with a message pointing at `ipfs-message-port-server`

**Comment by lidel** [comment]
Done!
